### ISSUE TITLE
how could map remove item?

### ISSUE THREAD

**Issue by songtzu** [giacomodrago/fcmm#1]
as readme.md said,it support only insert and update, how could we remove item from it?

**Comment by giacomodrago** [comment]
You cannot. The map is designed to be used for memoization (see `cppmemo` for a real-world use case), and not for anything else (e.g. storing sessions), for which you may use any of the existing solutions (e.g. `tbb::concurrent_hash_map`, folly's `AtomicHashMap`). Basically, you'll get lightning fast performance in a very specific scenario.
